### ISSUE TITLE
Skin is missing stuff, crashes when trying to move either right ot left

### ISSUE THREAD

**Issue by zkvsky** [oomek/ambience-hd#1] opened 2019-11-30 20:57 UTC
In progress...

Initially

![Screenshot_20191130_201159](https://user-images.githubusercontent.com/1215421/69906000-ca7a1800-13bc-11ea-9916-10feb12d2bb2.png)

after adding to every .vert & .frag  `#version 130` ( in modern_dialogs too )

![Screenshot_20191130_220241](https://user-images.githubusercontent.com/1215421/69906024-3d838e80-13bd-11ea-8efb-6f55b88680df.png)

moving right or left still crashes layout, and this blank popup appears initially
snaps in thumb and in the background play properly

**Comment by zkvsky** [comment] 2019-11-30 21:29
Current log (edited out ROM/assets related stuff): 
Can't figure out the one shader left which still can't compile

```
./attract --loglevel debug
Attract-Mode v2.6.0 (Linux, SFML 2.5.1 +FontConfig +Xinerama +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100



`***` Initializing display: 'Sega Saturn'
//Snip Snip
Joysticks after mapping: 
ID: 0 => Joy0(Sony Interactive Entertainment Wireless Controller)
ID: 1 => Joy7(No Joystick)
ID: 2 => Joy7(No Joystick)
ID: 3 => Joy7(No Joystick)
ID: 4 => Joy7(No Joystick)
ID: 5 => Joy7(No Joystick)
ID: 6 => Joy7(No Joystick)
ID: 7 => Joy7(No Joystick)
Created Attract-Mode Window: 1920x1080 @ 0,0 [OpenGL surface: 1920x1080 bpp=24]
Running script: /home/gregory/.attract/intro/intro.nut
Done script: /home/gregory/.attract/intro/intro.nut
Running script: /home/gregory/.attract/layouts/Arcadeflow/layout.nut
Running script: /home/gregory/.attract/modules/file.nut
Done script: /home/gregory/.attract/modules/file.nut
Running script: /home/gregory/.attract/layouts/Arcadeflow/pic_functions.nut
Done script: /home/gregory/.attract/layouts/Arcadeflow/pic_functions.nut
FFmpeg: Skipping 0 bytes of junk at 417.
FFmpeg: Skipping 0 bytes of junk at 417.
//Snip Snip
Done script: /home/gregory/.attract/layouts/Arcadeflow/layout.nut
 - Loaded layout: /home/gregory/.attract/layouts/Arcadeflow/ (layout.nut)
[Transition] type=StartLayout, var=2
[Transition] type=ToNewList, var=0
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Handling command: displays_menu
[Transition] type=ShowOverlay, var=12
FFmpeg: Reinit context to 640x480, pix_fmt: yuv420p
FFmpeg: Trying to use DRM render node for device 0.
FFmpeg: libva: VA-API version 1.5.0
FFmpeg: libva: va_getDriverName() returns 0
FFmpeg: libva: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
FFmpeg: libva: Found init function __vaDriverInit_1_5
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
FFmpeg: libva: va_openDriver() returns 0
FFmpeg: Initialised VAAPI connection: version 1.5
FFmpeg: VAAPI driver: Mesa Gallium driver 20.0.0-devel for AMD RAVEN (DRM 3.35.0, 5.4.0-gentoo-x86_64, LLVM 10.0.0).
FFmpeg: Driver not found in known nonstandard list, using standard behaviour.
created hw device: vaapi
FFmpeg: Reinit context to 640x480, pix_fmt: vaapi_vld
HWAccel output pixel format: nv12
FFmpeg: Reinit context to 640x480, pix_fmt: yuv420p
FFmpeg: Trying to use DRM render node for device 0.
FFmpeg: libva: VA-API version 1.5.0
FFmpeg: libva: va_getDriverName() returns 0
FFmpeg: libva: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
FFmpeg: libva: Found init function __vaDriverInit_1_5
FFmpeg: libva: va_openDriver() returns 0
FFmpeg: Initialised VAAPI connection: version 1.5
FFmpeg: VAAPI driver: Mesa Gallium driver 20.0.0-devel for AMD RAVEN (DRM 3.35.0, 5.4.0-gentoo-x86_64, LLVM 10.0.0).
FFmpeg: Driver not found in known nonstandard list, using standard behaviour.
created hw device: vaapi
FFmpeg: Reinit context to 640x480, pix_fmt: vaapi_vld
HWAccel output pixel format: nv12
Initializing resampler: in_sample_fmt=fltp, in_sample_rate=24000, out_sample_fmt=s16, out_sample_rate=24000
Initializing resampler: in_sample_fmt=fltp, in_sample_rate=24000, out_sample_fmt=s16, out_sample_rate=24000
[Transition] type=NewSelOverlay, var=3
[Transition] type=HideOverlay, var=0

*** Initializing display: 'Sega Dreamcast'
//Snip Snip
 - Loaded master romlist 'Sega Dreamcast' in 0 ms (10 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (20 comparisons)
[Transition] type=EndLayout, var=0
End Video Thread - /run/media/gregory/ZINE/ROMS/saturn/assets/videos/Sega Rally Championship (Europe) (Made in EU).mp4
 - bit_rate=1133611, width=640, height=480
 - displayed=114
 - average qscore=15
End Video Thread - /run/media/gregory/ZINE/ROMS/saturn/assets/videos/Sega Rally Championship (Europe) (Made in EU).mp4
 - bit_rate=1133611, width=640, height=480
 - displayed=115
 - average qscore=15
Running script: /home/gregory/.attract/layouts/Ambience HD/layout.nut
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
FFmpeg: parser not found for codec pcm_s16le, packets or times may be invalid.
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/math.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/math.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/frame_selector.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/frame_selector.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/frame_tile.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/frame_tile.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/animate.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/animate.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/carrier.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/carrier.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/text_scaled.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/text_scaled.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/blur.nut
Uniform "texsize" not found in shader
Uniform "texsize" not found in shader
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/blur.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/alphabet.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/alphabet.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/nuts/filters.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/nuts/filters.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/config.ini
Done script: /home/gregory/.attract/layouts/Ambience HD/config.ini
Running script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/initialize.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/math.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/math.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/modern_dialog.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/modern_dialog.nut
Running script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/modern_dialog_animate.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/modern_dialog_animate.nut
Failed to compile vertex shader:
0:11(22): error: vector size mismatch for arithmetic operator

Failed to compile vertex shader:
0:8(2): error: value of type vec4 cannot be assigned to variable of type vec2

Failed to compile vertex shader:
0:8(2): error: value of type vec4 cannot be assigned to variable of type vec2

Done script: /home/gregory/.attract/layouts/Ambience HD/modern_dialogs/initialize.nut
Done script: /home/gregory/.attract/layouts/Ambience HD/layout.nut
 - Loaded layout: /home/gregory/.attract/layouts/Ambience HD/ (layout.nut)
[Transition] type=StartLayout, var=0
//Snip Snip
[Transition] type=ToNewList, var=0
FFmpeg: Reinit context to 640x480, pix_fmt: yuv420p
FFmpeg: Trying to use DRM render node for device 0.
FFmpeg: libva: VA-API version 1.5.0
FFmpeg: libva: va_getDriverName() returns 0
FFmpeg: libva: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
FFmpeg: libva: Found init function __vaDriverInit_1_5
FFmpeg: libva: va_openDriver() returns 0
FFmpeg: Initialised VAAPI connection: version 1.5
FFmpeg: VAAPI driver: Mesa Gallium driver 20.0.0-devel for AMD RAVEN (DRM 3.35.0, 5.4.0-gentoo-x86_64, LLVM 10.0.0).
FFmpeg: Driver not found in known nonstandard list, using standard behaviour.
created hw device: vaapi
FFmpeg: Reinit context to 640x480, pix_fmt: vaapi_vld
HWAccel output pixel format: nv12
Initializing resampler: in_sample_fmt=fltp, in_sample_rate=24000, out_sample_fmt=s16, out_sample_rate=24000
Handling command: prev_display

*** Initializing display: 'Sega Saturn'
//Snip Snip;
 - Loaded master romlist 'Sega Saturn' in 0 ms (5 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (10 comparisons)
[Transition] type=EndLayout, var=0
End Video Thread - /run/media/gregory/ZINE/ROMS/dreamcast/assets/videos/Rez (Europe) (En,Ja,Fr,De,Es,It).mp4
 - bit_rate=976571, width=640, height=480
 - displayed=93
 - average qscore=15
Running script: /home/gregory/.attract/layouts/Arcadeflow/layout.nut
Running script: /home/gregory/.attract/modules/file.nut
Done script: /home/gregory/.attract/modules/file.nut
Running script: /home/gregory/.attract/layouts/Arcadeflow/pic_functions.nut
Done script: /home/gregory/.attract/layouts/Arcadeflow/pic_functions.nut
FFmpeg: Skipping 0 bytes of junk at 417.
FFmpeg: Skipping 0 bytes of junk at 417.
Done script: /home/gregory/.attract/layouts/Arcadeflow/layout.nut
 - Loaded layout: /home/gregory/.attract/layouts/Arcadeflow/ (layout.nut)
[Transition] type=StartLayout, var=0
[Transition] type=ToNewList, var=0
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
Uniform "enabled" not found in shader
FFmpeg: Reinit context to 640x480, pix_fmt: yuv420p
FFmpeg: Trying to use DRM render node for device 0.
FFmpeg: libva: VA-API version 1.5.0
FFmpeg: libva: va_getDriverName() returns 0
FFmpeg: libva: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
FFmpeg: libva: Found init function __vaDriverInit_1_5
FFmpeg: libva: va_openDriver() returns 0
FFmpeg: Initialised VAAPI connection: version 1.5
FFmpeg: VAAPI driver: Mesa Gallium driver 20.0.0-devel for AMD RAVEN (DRM 3.35.0, 5.4.0-gentoo-x86_64, LLVM 10.0.0).
FFmpeg: Driver not found in known nonstandard list, using standard behaviour.
created hw device: vaapi
FFmpeg: Reinit context to 640x480, pix_fmt: vaapi_vld
HWAccel output pixel format: nv12
FFmpeg: Reinit context to 640x480, pix_fmt: yuv420p
FFmpeg: Trying to use DRM render node for device 0.
FFmpeg: libva: VA-API version 1.5.0
FFmpeg: libva: va_getDriverName() returns 0
FFmpeg: libva: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
FFmpeg: libva: Found init function __vaDriverInit_1_5
FFmpeg: libva: va_openDriver() returns 0
FFmpeg: Initialised VAAPI connection: version 1.5
FFmpeg: VAAPI driver: Mesa Gallium driver 20.0.0-devel for AMD RAVEN (DRM 3.35.0, 5.4.0-gentoo-x86_64, LLVM 10.0.0).
FFmpeg: Driver not found in known nonstandard list, using standard behaviour.
created hw device: vaapi
FFmpeg: Reinit context to 640x480, pix_fmt: vaapi_vld
HWAccel output pixel format: nv12
Initializing resampler: in_sample_fmt=fltp, in_sample_rate=24000, out_sample_fmt=s16, out_sample_rate=24000
Initializing resampler: in_sample_fmt=fltp, in_sample_rate=24000, out_sample_fmt=s16, out_sample_rate=24000
Handling command: exit
[Transition] type=ShowOverlay, var=22
[Transition] type=NewSelOverlay, var=0
[Transition] type=HideOverlay, var=0
End Video Thread - /run/media/gregory/ZINE/ROMS/saturn/assets/videos/Sega Rally Championship (Europe) (Made in EU).mp4
 - bit_rate=1133611, width=640, height=480
 - displayed=212
 - average qscore=15
End Video Thread - /run/media/gregory/ZINE/ROMS/saturn/assets/videos/Sega Rally Championship (Europe) (Made in EU).mp4
 - bit_rate=1133611, width=640, height=480
 - displayed=212
 - average qscore=15
[Transition] type=EndLayout, var=2
Attract-Mode ended normally

```

**Comment by oomek** [comment] 2019-11-30 21:32
Thanks for the logs.
I'm gonna check on VM with Ubuntu and try to get to the bottom of this.

**Comment by zkvsky** [comment] 2019-11-30 21:39
> Thanks for the logs.
> I'm gonna check on VM with Ubuntu and try to get to the bottom of this.

I can check how it behaves under  win 10 if it's any help, same machine.

**Comment by oomek** [comment] 2019-11-30 21:54
It would be helpful.

**Comment by oomek** [comment] 2019-12-01 01:08
Please check this branch and tell me if it helped.
https://github.com/oomek/ambience-hd/tree/linux-compatibility

**Comment by zkvsky** [comment] 2019-12-01 11:06
> Please check this branch and tell me if it helped.
> https://github.com/oomek/ambience-hd/tree/linux-compatibility

Great! Just tested it:
![Screenshot_20191201_115857](https://user-images.githubusercontent.com/1215421/69913001-35196b00-1432-11ea-9cc6-939643396a57.png)

Now it's on par with what  I have under win 10. Including the same remaining bugs.
When trying to move right or left, by one thumb it apparently switches displays [ i.e I'm in N64, move one to the left and I'm suddenly in Dreamcast thumbs ] by one more and the layout crashes.
I can't see anything in the log, it was happening previously too, on my previous log.
[ oh and it's missing header logo and  the bottom bar, they're there under win 10 ]

**Comment by oomek** [comment] 2019-12-01 11:40
Please follow the issue https://github.com/oomek/ambience-hd/issues/3

**Comment by zkvsky** [comment] 2019-12-01 11:43
> Please follow the issue #3
@oomek Yup, just saw it, thanks!

**Comment by oomek** [comment] 2019-12-01 11:45
If it's all solved please close the issue

**Comment by oomek** [comment] 2019-12-01 11:59
Uh, the logo's missing and the bar, Will look into it, but debugging it under virtual machine is a pain in the rear as I'm getting no more than 5fps

**Comment by zkvsky** [comment] 2019-12-01 12:09
> Uh, the logo's missing and the bar, Will look into it, but debugging it under virtual machine is a pain in the rear as I'm getting no more than 5fps

I could set up accelerated one you could vnc into, it would take a bit
[ actually you could vnc into my real one, into container or something, depends on what kind of enviro you want ]
What are you using for VM, shouldn't it be accelerated?

**Comment by oomek** [comment] 2019-12-01 12:14
Cool, nothing fancy, just an AM shortcut and access to the folder with Ambience
Some pngs are not loading due to 
`Failed to load image from stream. Reason: PNG not supported: 1/2/4/8-bit only`

The bottom bar is showing on my VM. Can you check if it's enabled in layout settings?

I'm running the latest Ubuntu on  VBox with HW accel enabled VBoxSVGA + 3D accel. with VMSVGA it crashes

**Comment by zkvsky** [comment] 2019-12-01 12:22
@oomek 
Yup, it was disabled... bar shows up, missing header logo left.
You could try [VMware Workstation Player](https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/15_0)  it should run much better. VBox sucks at accel

**Comment by oomek** [comment] 2019-12-01 12:27
It's just that I forgot Linux is case sensitive. rename the file to `arcade.png`

**Comment by oomek** [comment] 2019-12-01 12:28
I've just literally went back to VBox from VMWare as it was crashing constantly on copying files by drag&drop

**Comment by zkvsky** [comment] 2019-12-01 13:47
> It's just that I forgot Linux is case sensitive. rename the file to `arcade.png`

Yup fixed, I think this one can be closed, I'd still consider controls a bug as I'm having issues figuring it out and it's messing with my other layouts.
Why are there logos for other platforms, are they used in any way or it's a future work?

[ gotta fix my missing metadata, overwiews...]

**Comment by oomek** [comment] 2019-12-01 13:48
It can stay open until I get it working without remapping controls.

**Comment by oomek** [comment] 2019-12-01 13:56
These other logos are there just to test the system selector I'll be working on.

**Comment by zkvsky** [comment] 2019-12-01 14:11
> These other logos are there just to test the system selector I'll be working on.

Can't wait! This theme makes me want to build a dedicated system...

**Comment by zkvsky** [comment] 2019-12-05 06:51
@oomek I've seen progress on the navigation, in the meantime I've found one really annoying and one small bug.
When Display doesn't have any filters pressing up will crash AM, restart will result in black screen and inability to do anything, adding any filter manually in the config file fixes it.
The other one, when going down through filters thumb descriptions disappear.

I've set up small container for ya at my box, let me know if it's of any use for ya. Should be way smoother than 5fps. I've pmed you creds via AM forum.

[ I'm not sure if PMs work at AM forum though... ]

**Comment by oomek** [comment] 2019-12-05 07:11
Thanks for the report, I'm gonna fix that tomorrow. I was occupied by adding a new feature to Attract Mode for the last 2 days.

All power commands are Windows speciffic, you have to edit config.ini

For thumb description I'm gonna need more data so I can reproduce this here.

Thank you for the client

**Comment by zkvsky** [comment] 2019-12-05 11:55
I didn't mean that restart causes a black screen, I meant that after force closing and reopening you'll get perma black screen, when pressing up on display with zero filters.
With thumbs, to clarify, I meant titles, genre etc. just going down through the filters makes them disappear, go up and they're there again. You can see it for yourself on my box


( I'm just putting it out there, in no way I'm trying to rush you, there's no rush ;) )

**Comment by oomek** [comment] 2019-12-05 14:14
You may want to check the latest release in master branch:
https://github.com/oomek/ambience-hd

**Closed as completed** 2020-03-03 19:44 UTC
